# -*- mode: ruby -*-
# vi: set ft=ruby :

# base of ips that will be user
base_ip="192.168.21."

# first ip to be used
first_ip=60

# the number of pxc nodes
number_of_slaves=2

#one server is the master
number_of_slaves += 1

# create an array to store the list of ips
ips = [ "#{base_ip}#{first_ip}" ]

# build the list of ips for each node and gcomm address
(1..number_of_slaves).each do |a|
  first_ip += 1
  ips.push("#{base_ip}#{first_ip}")
end

Vagrant.configure(2) do |config|
  (1..number_of_slaves).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.host_name = "node#{i}"
      node.vm.network "private_network", ip:ips[i]
      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
#        if i == 3
#	  vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
#        end
      end
      node.vm.provision :shell do |s|
        s.path = "provision_node.sh"
        s.args = [i, ips[i], ips[1]]
      end
    end
  end
  config.vm.define "mha" do |mha|
    mha.vm.box = "centos/7"
    mha.vm.host_name = "mha"
    mha.vm.network "private_network", ip:ips[0]
    mha.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end

    # remove the first ip from ips (proxy ip)
    mha.vm.provision :shell do |s|
      s.path = "provision_mha.sh"
      s.args = number_of_slaves
    end
  end
end
