# -*- mode: ruby -*-
# vi: set ft=ruby :

# base of ips that will be user
base_ip="192.168.41."

# first ip to be used
first_ip=30

# the number of pxc nodes
number_of_nodes=2

# one node is master
number_of_nodes += 1
# create an array to store the list of ips
ips = [ "#{base_ip}#{first_ip}" ]

# build the list of ips for each node and gcomm address
(1..number_of_nodes).each do |a|
  ips.push("#{base_ip}#{first_ip}")
  first_ip += 1
end

Vagrant.configure(2) do |config|
  (1..number_of_nodes).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.host_name = "node#{i}"
      node.vm.network "private_network", ip:ips[i]
      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "8192"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
      node.vm.provision :shell do |s|
        s.path = "provision_node.sh"
        s.args = [i, ips[i], ips[1], number_of_nodes]
      end
      node.vm.synced_folder "./", "/shared"
    end
  end
end
