# -*- mode: ruby -*-
# vi: set ft=ruby :
ip_addr="192.168.23.44"
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.host_name = "vault"
  config.vm.network "private_network", ip: ip_addr
  config.vm.provision :shell do |s|
    s.path = "provision_vault.sh"
    s.args = [ip_addr]
  end
end
